function makeDerivativeDescription(pipelineDir)
%MAKE DERIVATIVEDESCRIPTION Ensure dataset_description.json exists for BIDS derivatives
%
% Usage:
%   makeDerivativeDescription(fullfile(root, 'derivatives', 'eeglab-ICA_pipeline'))

descFile = fullfile(pipelineDir, 'dataset_description.json');
if exist(descFile, 'file')
    return; % do nothing if already present
end

descStruct = struct( ...
    'Name', 'EEGLAB ICA preprocessing pipeline outputs', ...
    'BIDSVersion', '1.8.0', ...
    'DatasetType', 'derivative', ...
    'GeneratedBy', {struct( ...
        'Name', 'EEGLAB', ...
        'Version', '2024.0', ...
        'Description', 'EEGLAB pipeline with ICA preprocessing and channel locations', ...
        'CodeURL', 'https://github.com/sccn/eeglab')} , ...
    'SourceDatasets', {struct('Description', 'Raw BIDS EEG dataset')} ...
    );

jsonText = jsonencode(descStruct, 'PrettyPrint', true);
fid = fopen(descFile, 'w');
fwrite(fid, jsonText, 'char');
fclose(fid);

fprintf('Created BIDS dataset_description.json at %s\n', descFile);
end
